name: Go
on: [pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    # - name: Install golangci-lint
    #   run: |
    #     curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.30.0

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    # - name: Install Tools
    #   run: make install-tools

    # - name: Install Dependencies
    #   run: PATH="$(go env GOPATH)/bin":$PATH make vendor-dependencies

    - name: Lint
      run: make lint

    - name: Test
      run: make test-all

    - name: Build Tempo
      run: make tempo

    - name: Build Tempo-Query
      run: make tempo-query